apiVersion: v1
kind: ServiceAccount
metadata:
  name: rust-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: rust-role
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rust-binding
subjects:
- kind: ServiceAccount
  name: rust-sa
roleRef:
  kind: Role
  name: rust-role
  apiGroup: rbac.authorization.k8s.io
